name: 'netflix_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'netflix'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  netflix_project:
    # Default every model in this package to the curated transform schema
    +schema: DBT_TRANSFORM

    stage:
      # Stage layer should materialize as tables in PROD.DBT_TRANSFORM
      +materialized: table
      +schema: DBT_TRANSFORM

    dimension:
      # Dimension layer is published to the PROD analytics schema
      +materialized: table
      +schema: DBT_PROD

    fact:
      # Fact layer shares the same PROD analytics schema
      +materialized: table
      +schema: DBT_PROD

vars:
  titles_raw: 'PROD.DBT_RAW.TITLES'
  credits_raw: 'PROD.DBT_RAW.CREDITS'
